MAX_BLOCK_SERIALIZED_SIZE: 1000000
MAX_FUTURE_BLOCK_TIME: 7200
MINIS_PER_COIN: 1000000
TOTAL_COINS: 10000000
TIME_BETWEEN_BLOCKS_IN_SECS_TARGET: 60
DIFFICULTY_PERIOD_IN_SECS_TARGET: 36000
INITIAL_DIFFICULTY_BITS: 24
HALVE_SUBSIDY_AFTER_BLOCKS_NUM: 100000
COINBASE_MATURITY: 2
